export const recipes = [
    {
      id: 1,
      recipeName: "Spaghetti Bolognese",
      imageUrl:
        "https://images.pexels.com/photos/2433979/pexels-photo-2433979.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      ingredients: [
        "250g spaghetti",
        "400g ground beef",
        "1 onion, chopped",
        "2 garlic cloves, minced",
        "400g canned diced tomatoes",
        "1 tablespoon tomato paste",
        "1 teaspoon dried oregano",
        "1 teaspoon dried basil",
        "Salt and pepper to taste",
        "Parmesan cheese, grated (for garnish)",
      ],
      cookingInstructions: [
        "Cook the spaghetti according to package instructions until al dente.",
        "In a large pan, brown the ground beef over medium heat.",
        "Add the chopped onion and minced garlic to the pan, and sauté until the onion is translucent.",
        "Stir in the diced tomatoes, tomato paste, dried oregano, dried basil, salt, and pepper.",
        "Simmer the sauce for 15-20 minutes, allowing the flavors to meld together.",
        "Serve the sauce over the cooked spaghetti, and garnish with grated Parmesan cheese.",
      ],
      cuisineType: "Italian",
    },
    {
      id: 2,
      recipeName: "Chicken Curry",
      imageUrl:
        "https://images.pexels.com/photos/7353379/pexels-photo-7353379.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      ingredients: [
        "500g chicken breasts, cut into cubes",
        "2 tablespoons vegetable oil",
        "1 onion, finely chopped",
        "2 garlic cloves, minced",
        "2 tablespoons curry powder",
        "1 teaspoon ground turmeric",
        "1 teaspoon ground cumin",
        "1 teaspoon paprika",
        "400ml coconut milk",
        "Salt to taste",
        "Fresh cilantro, chopped (for garnish)",
      ],
      cookingInstructions: [
        "Heat the vegetable oil in a large pan over medium heat.",
        "Add the chopped onion and minced garlic, and sauté until the onion is golden brown.",
        "Add the chicken cubes to the pan, and cook until they are browned on all sides.",
        "Stir in the curry powder, ground turmeric, ground cumin, and paprika.",
        "Pour in the coconut milk and season with salt.",
        "Simmer the curry for 20-25 minutes, or until the chicken is cooked through and tender.",
        "Garnish with freshly chopped cilantro and serve with steamed rice or naan bread.",
      ],
      cuisineType: "Indian",
    },
    {
      id: 3,
      recipeName: "Caprese Salad",
      imageUrl:
        "https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      ingredients: [
        "2 large ripe tomatoes",
        "250g fresh mozzarella cheese",
        "1 bunch fresh basil leaves",
        "2 tablespoons extra virgin olive oil",
        "Salt and pepper to taste",
        "Balsamic glaze (optional, for drizzling)",
      ],
      cookingInstructions: [
        "Slice the tomatoes and fresh mozzarella cheese into equal-sized slices.",
        "Arrange the tomato and mozzarella slices on a platter, alternating them.",
        "Tuck fresh basil leaves between the tomato and mozzarella slices.",
        "Drizzle extra virgin olive oil over the salad.",
        "Season with salt and pepper to taste.",
        "Optionally, drizzle balsamic glaze over the salad for added flavor.",
        "Serve immediately as a refreshing appetizer or side dish.",
      ],
      cuisineType: "Italian",
    },
    {
      id: 4,
      recipeName: "Stir-Fried Beef with Vegetables",
      imageUrl:
        "https://images.pexels.com/photos/10262797/pexels-photo-10262797.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      ingredients: [
        "400g beef sirloin, thinly sliced",
        "2 tablespoons soy sauce",
        "2 tablespoons oyster sauce",
        "1 tablespoon cornstarch",
        "2 tablespoons vegetable oil",
        "1 onion, thinly sliced",
        "1 bell pepper, thinly sliced",
        "1 carrot, thinly sliced",
        "2 cloves garlic, minced",
        "1 teaspoon ginger, grated",
        "Salt and pepper to taste",
        "2 green onions, chopped (for garnish)",
      ],
      cookingInstructions: [
        "In a bowl, mix together soy sauce, oyster sauce, and cornstarch. Set aside.",
        "Heat vegetable oil in a wok or large skillet over high heat.",
        "Add the beef slices and stir-fry for 2-3 minutes until browned. Remove from the pan and set aside.",
        "In the same pan, add onion, bell pepper, carrot, garlic, and ginger. Stir-fry for 2-3 minutes until vegetables are crisp-tender.",
        "Return the beef to the pan and pour in the sauce mixture.",
        "Cook for an additional 2-3 minutes until the sauce thickens and coats the beef and vegetables.",
        "Season with salt and pepper to taste.",
        "Garnish with chopped green onions and serve hot with steamed rice or noodles.",
      ],
      cuisineType: "Asian",
    },
  ];